version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - internal_network

  backend:
    container_name: 'backend'
    build:
      context: ./BackendApplication/
      dockerfile: Dockerfile
    ports:
      - 5000:80
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge