version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 17558:5672
      - 17556:15672
    networks:
      - internal_network
  
  backend:
    image: 10.40.71.55:5000/si_175592_backend
    depends_on:
      - rabbitmq
    ports:
      - 17555:80
    networks:
      - internal_network
    restart: always
    
  frontend:
    image: 10.40.71.55:5000/si_175592_frontend
    ports:
      - 17559:8080
    networks:
      - internal_network
    stdin_open: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_SERVER_URL=http://localhost:17555/
    working_dir: /app

networks:
  internal_network:
    name: si_175592
    driver: overlay